// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.

namespace Asm6502;

/// <summary>
/// Specifies the kinds of debug information records that can be generated by a <see cref="Mos6502AssemblerBase"/> with the <see cref="IMos6502AssemblerDebugMap"/>.
/// </summary>
public enum Mos6502AssemblerDebugInfoKind
{
    /// <summary>
    /// Marks the beginning of an origin (ORG) region.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> might contains the origin name or expression.
    /// <see cref="Mos6502AssemblerDebugInfo.Address"/> is the base address.
    /// </summary>
    OriginBegin,

    /// <summary>
    /// Maps an assembled address to a source file and line.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> is the file path.
    /// <see cref="Mos6502AssemblerDebugInfo.LineNumber"/> is the 1-based line number.
    /// </summary>
    LineInfo,

    /// <summary>
    /// Marks entry into a code section.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> is the section name.
    /// </summary>
    CodeSectionBegin,

    /// <summary>
    /// Marks exit from a code section.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> is null.
    /// </summary>
    CodeSectionEnd,

    /// <summary>
    /// Marks entry into a data section.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> is the section name.
    /// </summary>
    DataSectionBegin,

    /// <summary>
    /// Marks exit from a data section.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> is null.
    /// </summary>
    DataSectionEnd,

    /// <summary>
    /// Marks the end of the debug stream.
    /// <see cref="Mos6502AssemblerDebugInfo.Name"/> and <see cref="Mos6502AssemblerDebugInfo.LineNumber"/> are null.
    /// </summary>
    End,
}